; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:giga_r1_m7]
platform = ststm32
board = giga_r1_m7
framework = arduino
lib_ldf_mode = deep+
board_build.arduino.flash_layout = 100_0
board_upload.maximum_size = 2097152
lib_deps = 
	arduino-libraries/Arduino_GigaDisplay_GFX@^1.1.0
	arduino-libraries/Arduino_GigaDisplay@^1.0.2
	arduino-libraries/Servo@^1.2.2
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit FRAM I2C@^2.0.3
	adafruit/Adafruit BusIO@^1.17.4
	adafruit/Adafruit Unified Sensor@^1.1.15
	arduino-libraries/ArduinoBLE@^2.0.1
	adafruit/Adafruit AS7341@^1.4.1
	sparkfun/SparkFun VL53L5CX Arduino Library@^1.0.3

